cleanup

diff --git a/build-image b/build-image
--- a/build-image
+++ b/build-image
@@ -15,10 +15,10 @@ EOF
     exit 1
 }
 
-function fatal {
-    echo "$PROG: ${1:-"Unknown Error"}" 1>&2
-    exit 1
-}
+# function fatal {
+#     echo "$PROG: ${1:-"Unknown Error"}" 1>&2
+#     exit 1
+# }
 
 function abspath {
     echo $(cd "$1" && pwd)
